run:
  timeout: 10m
  issues-exit-code: 1
  tests: true


linters-settings:
  govet: {}
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - performance
      - style
      - diagnostic
    disabled-checks:
      - wrapperFunc
      - dupImport
  funlen:
    lines: 120
    statements: 60
  gocognit:
    min-complexity: 35
  errcheck:
    check-type-assertions: true
    check-blank: false
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
      - name: var-naming
        disabled: true
  staticcheck:
    checks: ["all"]

linters:
  disable-all: true
  enable:
    # Error detection
    - errcheck
    - govet
    - shadow
    - staticcheck
    - ineffassign
    
    # Code quality
    - revive
    - gocritic
    - gocyclo
    
    # Style and formatting
    - misspell
    - whitespace
    
    # Bug prevention
    - bodyclose
    - rowserrcheck
    
    # Performance
    - prealloc
    - unconvert
    
    # Complexity
    - dupl
    - goconst
    
    # Security
    - gosec

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Ignore generated protobuf files
    - path: ".*\\.pb\\.go$"
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - gocognit
        - goconst
        - prealloc
    
    # Allow interface{} in legacy terraform plugin framework code (necessary for SDK compatibility)
    - text: "use `any` instead of `interface{}`"
      linters:
        - revive
      path: (utils|types)\.go$
    
    # Allow underscores in package names for Terraform provider v2 resources (required convention)
    - text: "var-naming: don't use an underscore in package name"
      linters:
        - revive
    
    # Allow underscores in v2 package names (Terraform convention)
    - path: "_v2/"
      text: "don't use an underscore in package name"
      linters:
        - revive
