version: 2
project_name: terraform-provider-kkp

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: provider
    main: ./
    binary: "terraform-provider-kkp_v{{ .Version }}"
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.providerAddress=registry.terraform.io/armagankaratosun/kkp

archives:
  - id: archive
    ids: [provider]
    # Terraform Registry expects zip and version without leading 'v'
    name_template: "{{ .ProjectName }}_{{ trimprefix .Version \"v\" }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - LICENSE
      - README.md

checksum:
  # Terraform Registry expects: terraform-provider-kkp_0.0.2_SHA256SUMS
  name_template: "{{ .ProjectName }}_{{ trimprefix .Version \"v\" }}_SHA256SUMS"
  algorithm: sha256

signs:
  # Sign the SHA256SUMS file with GPG; requires GPG key available on runner
  - artifacts: checksum
    cmd: gpg
    signature: "${artifact}.sig"
    args:
      - "--batch"
      - "--yes"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase"
      - "{{ .Env.GPG_PASSPHRASE }}"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  draft: false
  prerelease: auto

changelog:
  use: git
  sort: asc
  groups:
    - title: Breaking Changes
      regexp: '(^.+!:)|(BREAKING CHANGE)'
      order: 0
    - title: Features
      regexp: '^feat(\(.+\))?:'
      order: 10
    - title: Fixes
      regexp: '^fix(\(.+\))?:'
      order: 20
    - title: Performance
      regexp: '^perf(\(.+\))?:'
      order: 30
    - title: Refactor
      regexp: '^refactor(\(.+\))?:'
      order: 40
    - title: Docs
      regexp: '^docs(\(.+\))?:'
      order: 50
    - title: CI/Build
      regexp: '^(ci|build)(\(.+\))?:'
      order: 60
  filters:
    exclude:
      - '^chore(\(.+\))?:'
      - '^test(\(.+\))?:'
      - '^revert(\(.+\))?:'
      - 'Merge pull request'
      - 'Merge branch'
      - '^bump'
      - '^release:'
