version: 2
project_name: terraform-provider-kkp

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: provider
    main: ./
    binary: terraform-provider-kkp
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.providerAddress=registry.terraform.io/armagankaratosun/kkp
  - id: provider-tofu
    main: ./
    binary: terraform-provider-kkp
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.providerAddress=registry.opentofu.org/armagankaratosun/kkp

archives:
  - id: archive
    ids: [provider]
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
  - id: archive_tofu
    ids: [provider-tofu]
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}_tofu"
    format: tar.gz
    overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  draft: false
  prerelease: auto

changelog:
  use: git
  sort: asc
  groups:
    - title: Breaking Changes
      regexp: '(^.+!:)|(BREAKING CHANGE)'
      order: 0
    - title: Features
      regexp: '^feat(\(.+\))?:'
      order: 10
    - title: Fixes
      regexp: '^fix(\(.+\))?:'
      order: 20
    - title: Performance
      regexp: '^perf(\(.+\))?:'
      order: 30
    - title: Refactor
      regexp: '^refactor(\(.+\))?:'
      order: 40
    - title: Docs
      regexp: '^docs(\(.+\))?:'
      order: 50
    - title: CI/Build
      regexp: '^(ci|build)(\(.+\))?:'
      order: 60
  filters:
    exclude:
      - '^chore(\(.+\))?:'
      - '^test(\(.+\))?:'
      - '^revert(\(.+\))?:'
      - 'Merge pull request'
      - 'Merge branch'
      - '^bump'
      - '^release:'
