#!/usr/bin/env sh
set -eu

# Usage: EXAMPLE_DIRS="dir1 dir2 ..." scripts/gen-examples.sh [OUTPUT]
OUTPUT=${1:-docs/guides/examples.md}

mkdir -p "$(dirname "$OUTPUT")"

{
  printf '%s\n' '---'
  printf '%s\n' '# generated by script'
  printf '%s\n' 'page_title: "Examples - terraform-provider-kkp"'
  printf '%s\n' 'description: |-'
  printf '%s\n' '  Reference examples for the KKP provider.'
  printf '%s\n' '---'
  printf '\n# Examples\n\n'

  for d in ${EXAMPLE_DIRS:-}; do
    [ -d "$d" ] || continue
    name=$(printf '%s' "$d" | sed 's#^examples/##')
    printf '## %s\n' "$name"
    if [ -f "$d/README.md" ]; then
      printf '\nSee README: [%s/README.md](%s/README.md)\n' "$name" "$d"
    fi
    for f in main.tf variables.tf; do
      if [ -f "$d/$f" ]; then
        printf '\n### %s\n\n' "$f"
        printf '\```hcl\n'
        # trim trailing whitespace
        sed -e 's/[[:space:]]\+$//' "$d/$f"
        printf '\```\n'
      fi
    done
    printf '\n'
  done
} > "$OUTPUT"

echo "Wrote: $OUTPUT"
