name: changelog

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., v0.0.1). Leave blank to update Unreleased."
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install git-cliff (prebuilt binary)
        uses: taiki-e/install-action@v2
        with:
          tool: git-cliff@2.2.1

      - name: Generate changelog (Unreleased)
        if: ${{ inputs.version == '' }}
        run: |
          git-cliff --config cliff.toml --unreleased --output CHANGELOG.md

      - name: Normalize version input to v-prefixed tag
        if: ${{ inputs.version != '' }}
        run: |
          VER="${{ inputs.version }}"
          VER="${VER#v}"
          echo "CLIFF_TAG=v${VER}" >> $GITHUB_ENV
          echo "CLIFF_VERSION=${VER}" >> $GITHUB_ENV

      - name: Generate changelog (Release)
        if: ${{ inputs.version != '' }}
        run: |
          git-cliff --config cliff.toml --tag "$CLIFF_TAG" --output CHANGELOG.md

      - name: Set PR metadata
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            echo "PR_SUFFIX=${CLIFF_TAG}" >> $GITHUB_ENV
            echo "BRANCH_SUFFIX=${CLIFF_VERSION}" >> $GITHUB_ENV
          else
            echo "PR_SUFFIX=Unreleased" >> $GITHUB_ENV
            echo "BRANCH_SUFFIX=unreleased" >> $GITHUB_ENV
          fi

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "docs(changelog): update for ${{ env.PR_SUFFIX }}"
          title: "Update CHANGELOG for ${{ env.PR_SUFFIX }}"
          body: |
            Automated changelog update generated by git-cliff.

            - Config: `cliff.toml`
            - Mode: ${{ inputs.version != '' && 'release' || 'unreleased' }}
          branch: chore/update-changelog-${{ env.BRANCH_SUFFIX }}
          base: main
