name: changelog

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., 0.1.0). Leave blank to update Unreleased."
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate changelog (Unreleased)
        if: ${{ inputs.version == '' }}
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --unreleased --output CHANGELOG.md

      - name: Generate changelog (Release)
        if: ${{ inputs.version != '' }}
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --tag ${{ inputs.version }} --output CHANGELOG.md

      - name: Set PR metadata
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            echo "PR_SUFFIX=v${{ inputs.version }}" >> $GITHUB_ENV
            echo "BRANCH_SUFFIX=${{ inputs.version }}" >> $GITHUB_ENV
          else
            echo "PR_SUFFIX=Unreleased" >> $GITHUB_ENV
            echo "BRANCH_SUFFIX=unreleased" >> $GITHUB_ENV
          fi

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "docs(changelog): update for ${{ env.PR_SUFFIX }}"
          title: "Update CHANGELOG for ${{ env.PR_SUFFIX }}"
          body: |
            Automated changelog update generated by git-cliff.

            - Config: `cliff.toml`
            - Mode: ${{ inputs.version != '' && 'release' || 'unreleased' }}
          branch: chore/update-changelog-${{ env.BRANCH_SUFFIX }}
          base: main
