name: ci

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  workflow-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint GitHub Actions workflows (actionlint)
        uses: rhysd/actionlint@v1.7.1

  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Go modules cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: Build provider and set Terraform dev overrides
        run: |
          set -euo pipefail
          # Build the provider with the resolved VERSION (from tag or VERSION file)
          make build
          # Configure Terraform to use the locally built provider for validation
          cat > "$RUNNER_TEMP/tfrc" <<'RC'
          provider_installation {
            dev_overrides {
              "registry.terraform.io/armagankaratosun/kkp" = "$GITHUB_WORKSPACE/bin"
            }
            direct {}
          }
RC
          echo "TF_CLI_CONFIG_FILE=$RUNNER_TEMP/tfrc" >> "$GITHUB_ENV"

      - name: Check Terraform formatting in examples/
        run: |
          if [ -d examples ]; then
            terraform fmt -check -recursive examples
          else
            echo "No examples/ directory; skipping terraform fmt check"
          fi

      - name: Validate examples (terraform validate)
        run: make examples-validate

      - name: Validate examples (terraform validate)
        run: |
          set -euo pipefail
          if [ -d examples ]; then
            find examples -type f -name 'main.tf' | while read -r f; do
              d=$(dirname "$f")
              echo "==> Validating $d"
              (cd "$d" && terraform init -backend=false -input=false -upgrade && terraform validate -no-color)
            done
          else
            echo "No examples/ directory; skipping terraform validate"
          fi

      - name: Check formatting (gofmt -s)
        run: |
          unformatted=$(gofmt -s -l .)
          if [ -n "$unformatted" ]; then
            echo "Files not gofmt'ed:" >&2
            echo "$unformatted" >&2
            exit 1
          fi

      - name: Lint (golangci-lint)
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m --config=.golangci.yml

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...
