name: release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install tfplugindocs
        if: ${{ github.ref_type == 'tag' }}
        run: |
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
          go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@latest

      - name: Import GPG key (optional)
        if: ${{ github.ref_type == 'tag' && secrets.GPG_PRIVATE_KEY != '' }}
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          # Prefer base64-encoded secret; fallback to plain armored import
          if echo "$GPG_PRIVATE_KEY" | base64 -d >/tmp/gpg.key 2>/dev/null; then
            gpg --batch --import /tmp/gpg.key
            rm -f /tmp/gpg.key
          else
            printf '%s' "$GPG_PRIVATE_KEY" | gpg --batch --import
          fi
          # Export fingerprint for signing
          KEY_ID=$(gpg --batch --list-secret-keys --with-colons | awk -F: '/^sec:/{print $5; exit}')
          echo "GPG_FINGERPRINT=$KEY_ID" >> "$GITHUB_ENV"

      - name: Verify docs up-to-date (make docs)
        if: ${{ github.ref_type == 'tag' }}
        run: |
          make docs
          if ! git diff --quiet -- docs; then
            echo "Docs are outdated for this release tag. Run 'make docs' and commit before tagging." >&2
            git --no-pager diff -- docs || true
            exit 1
          fi

      - name: Run GoReleaser (tagged release)
        if: ${{ github.ref_type == 'tag' }}
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v2.12.0
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run GoReleaser (snapshot on manual/branch run)
        if: ${{ github.ref_type != 'tag' }}
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v2.12.0
          args: release --clean --skip=publish --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
